# constants.py
# Column name constants
TARGET = 'TargetFileDescr'
SEGMENT = 'segment'
DATE_DEPART_END_OF_MONTH = 'dateDepart_EndOfMonth'
POLICY_SOLD_COUNT = 'policy_sold_count'
POLICY_COUNT = 'policy_count'
CLAIM_COUNT = 'claim_count'
CLAIM_CUMUL = 'claim_cumul'
CLAIM_NUM_UNIQUE = 'clmNum_unique'
DEPARTURE_YEAR = 'departure_year'
DEPARTURE_MONTH = 'departure_month'
CAT_CODE = 'catCode'
FREQUENCY_VAL = 'frequency_val'
FREQUENCY_CUMUL = 'frequency_cumul'
SOLD_DAY = 'dateApp'
DATE_SOLD_END_OF_MONTH = 'dateApp_EndOfMonth'
DEPARTURE_DAY = 'dateDepart'
RECEIVED_DAY = 'dateReceived'
DATE_RECEIVED_END_OF_MONTH = 'dateReceived_EndOfMonth'
PERIOD = 'period'
DEVELOPMENT = 'development'
IS_MAJOR_CAT = 'is_major_cat'
#DEVELOPMENT_FACTOR = 'development_factor'
DEVELOPMENT_FACTOR = 'development_factor'
PREV_FREQUENCY_CUMUL = 'prev_frequency_cumul'
ULTIMATE_FREQUENCY = 'ultimate_frequency'
CURRENT_FREQUENCY = 'current_frequency'